apiVersion: v1
entries:
  passbolt-library:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-02-07T11:08:18.673202029Z"
    description: Helm chart that contains passbolt common templates
    digest: 9af5e7aa9acaed8c95e376453cd8ad35e921f46b762679b2ca89ba078af61399
    name: passbolt-library
    type: library
    urls:
    - https://passbolt.gitlab.io/passbolt-ops/passbolt-helm-library/passbolt-library-0.2.7.tgz
    version: 0.2.7
generated: "2023-02-07T11:08:18.672508117Z"
