{{- if .Values.cronJobCleanDB.serviceAccount.create -}}
{{- $type := "sa" -}}
{{- $action := "clean-db" -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: passbolt
  labels:
    {{- include "passbolt-library.labels" . | nindent 4 }}
    {{- include "passbolt-library.selectorLabels" . | nindent 4 }}
    {{- include "passbolt-library.typelabels" (dict "action" $action "type" $type) | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}