{{- if .Values.externalSecrets.create -}}
{{- $type := "sec" -}}
{{- $action := "env" -}}
{{- $Name := include "passbolt-library.fullname" . -}}
{{- $secretStore := printf "%s-secretstore-%s" $Name $action -}}
{{- $fullName := printf "%s-%s-%s" $Name $type $action -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: external-secrets.io/v1beta1
{{- else -}}
apiVersion: external-secrets.io/v1alpha1
{{- end }}
kind: ExternalSecret
metadata:
  name: {{ $fullName }}
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: {{ $secretStore }}
    kind: SecretStore
  target:
    name: {{ $fullName }}
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: CACHE_CAKE_DEFAULT_SERVER # secret data
    remoteRef:
      key: {{ .Values.externalSecrets.env.path }}
      property: CACHE_CAKE_DEFAULT_SERVER    # vault key
  - secretKey: CACHE_CAKE_DEFAULT_PORT # secret data
    remoteRef:
      key: {{ .Values.externalSecrets.env.path }}
      property: CACHE_CAKE_DEFAULT_PORT    # vault key
  - secretKey: CACHE_CAKE_DEFAULT_PASSWORD # secret data
    remoteRef:
      key: {{ .Values.externalSecrets.env.path }}
      property: CACHE_CAKE_DEFAULT_PASSWORD    # vault key
  - secretKey: DATASOURCES_DEFAULT_HOST # secret data
    remoteRef:
      key: {{ .Values.externalSecrets.env.path }}
      property: DATASOURCES_DEFAULT_HOST    # vault key
  - secretKey: DATASOURCES_DEFAULT_PORT # secret data
    remoteRef:
      key: {{ .Values.externalSecrets.env.path }}
      property: DATASOURCES_DEFAULT_PORT    # vault key
  - secretKey: DATASOURCES_DEFAULT_USERNAME # secret data
    remoteRef:
      key: {{ .Values.externalSecrets.env.path }}
      property: DATASOURCES_DEFAULT_USERNAME    # vault key
  - secretKey: DATASOURCES_DEFAULT_DATABASE # secret data
    remoteRef:
      key: {{ .Values.externalSecrets.env.path }}
      property: DATASOURCES_DEFAULT_DATABASE    # vault key
  - secretKey: DATASOURCES_DEFAULT_PASSWORD # secret data
    remoteRef:
      key: {{ .Values.externalSecrets.env.path }}
      property: DATASOURCES_DEFAULT_PASSWORD    # vault key
  - secretKey: EMAIL_TRANSPORT_DEFAULT_USERNAME # secret data
    remoteRef:
      key: {{ .Values.externalSecrets.env.path }}
      property: EMAIL_TRANSPORT_DEFAULT_USERNAME    # vault key
  - secretKey: EMAIL_TRANSPORT_DEFAULT_PASSWORD # secret data
    remoteRef:
      key: {{ .Values.externalSecrets.env.path }}
      property: EMAIL_TRANSPORT_DEFAULT_PASSWORD    # vault key
  - secretKey: PASSBOLT_GPG_SERVER_KEY_FINGERPRINT # secret data
    remoteRef:
      key: {{ .Values.externalSecrets.env.path }}
      property: PASSBOLT_GPG_SERVER_KEY_FINGERPRINT    # vault key
  - secretKey: PASSBOLT_KEY_EMAIL # secret data
    remoteRef:
      key: {{ .Values.externalSecrets.env.path }}
      property: PASSBOLT_KEY_EMAIL    # vault key
{{- end }}
      