{{- if .Values.externalSecrets.create -}}
{{- $type := "sec" -}}
{{- $action := "gpg" -}}
{{- $Name := include "passbolt-library.fullname" . -}}
{{- $secretStore := printf "%s-secretstore-%s" $Name $action -}}
{{- $fullName := printf "%s-%s-%s" $Name $type $action -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: external-secrets.io/v1beta1
{{- else -}}
apiVersion: external-secrets.io/v1alpha1
{{- end }}
kind: ExternalSecret
metadata:
  name: {{ $fullName }}
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: {{ $secretStore }}
    kind: SecretStore
  target:
    name: {{ $fullName }}
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: serverkey.asc # secret data
    remoteRef:
      key: {{ .Values.externalSecrets.gpg.path }}
      property: serverkey.asc    # vault key
  - secretKey: serverkey_private.asc # secret data
    remoteRef:
      key: {{ .Values.externalSecrets.gpg.path }}
      property: serverkey_private.asc    # vault key
{{- end }}
      