{{- if .Values.externalSecrets.create }}
{{- $type := "secretstore" -}}
{{- $action := "jwt" -}}
{{- $Name := include "passbolt-library.fullname" . -}}
{{- $fullName := printf "%s-%s-%s" $Name $type $action -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: external-secrets.io/v1beta1
{{- else -}}
apiVersion: external-secrets.io/v1alpha1
{{- end }}
kind: SecretStore
metadata:
  name: {{ $fullName }}
spec:
  provider:
    {{- with .Values.externalSecrets.vault }}
    vault:
      {{- toYaml . | nindent 6 }}
    {{- end }}  
{{- end }}    
